# 2 rules of properties file

# (hash symbol)- refers to comments in properties file
# property file stores configuration data in the form of key value pairs seperated by '=' symbol

#Application configurations
app.url = https://accounts.creatio.com/login/alm
app.username=bharattechacademy3@outlook.com
app.password=BharathTechAcademy#1234
app.title=Log in 

#Browser configurations
browser.name=chrome

#DB configurations
db.url=jdbc.postgresql://localhost:5432/dvdrental
db.username=postgres
db.password=admin

#API Configurations
api.baseurl= https://api.github.com
github.username= sangeemano25
#git.token= Bearer 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